src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $nbPlace = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateDebut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateFin = null;

    #[ORM\ManyToMany(targetEntity: Stagiaire::class, inversedBy: 'sessions')]
    private Collection $inscriptions;

    #[ORM\OneToMany(targetEntity: Programme::class, mappedBy: 'session', orphanRemoval: true)]
    private Collection $programmes;

    #[ORM\Column(length: 80, nullable: true)]
    private ?string $titre = null;

    #[ORM\ManyToOne(inversedBy: 'sessions')]
    private ?Formation $formation = null;

    #[ORM\ManyToOne(inversedBy: 'sessions')]
    private ?Formateur $formateur = null;

    public function __construct()
    {
        $this->inscriptions = new ArrayCollection();
        $this->programmes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNbPlace(): ?int
    {
        return $this->nbPlace;
    }

    public function setNbPlace(int $nbPlace): static
    {
        $this->nbPlace = $nbPlace;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTimeInterface $dateDebut): static
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->dateFin;
    }

    public function setDateFin(\DateTimeInterface $dateFin): static
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    /**
     * @return Collection<int, Stagiaire>
     */
    public function getInscriptions(): Collection
    {
        return $this->inscriptions;
    }

    public function addInscription(Stagiaire $inscription): static
    {
        if (!$this->inscriptions->contains($inscription)) {
            $this->inscriptions->add($inscription);
        }

        return $this;
    }

    public function removeInscription(Stagiaire $inscription): static
    {
        $this->inscriptions->removeElement($inscription);

        return $this;
    }

    /**
     * @return Collection<int, Programme>
     */
    public function getProgrammes(): Collection
    {
        return $this->programmes;
    }

    public function addProgramme(Programme $programme): static
    {
        if (!$this->programmes->contains($programme)) {
            $this->programmes->add($programme);
            $programme->setSession($this);
        }

        return $this;
    }

    public function removeProgramme(Programme $programme): static
    {
        if ($this->programmes->removeElement($programme)) {
            // set the owning side to null (unless already changed)
            if ($programme->getSession() === $this) {
                $programme->setSession(null);
            }
        }

        return $this;
    }

    
    public function getTitre(): ?string
    {
        return $this->titre;
    }
    
    public function setTitre(?string $titre): static
    {
        $this->titre = $titre;
        
        return $this;
    }
    
    public function __toString()
    {
        return $this->titre;
    }

    public function getNbInscrit()
    {
        return count($this->inscriptions);
    }

    public function getNbPlacesRestantes()
    {
        return $this->nbPlace - $this->getNbInscrit();
    }

    public function getFormation(): ?Formation
    {
        return $this->formation;
    }

    public function setFormation(?Formation $formation): static
    {
        $this->formation = $formation;

        return $this;
    }

    public function getFormateur(): ?Formateur
    {
        return $this->formateur;
    }

    public function setFormateur(?Formateur $formateur): static
    {
        $this->formateur = $formateur;

        return $this;
    }

   
}

src/Form/SessionType.php
<?php

namespace App\Form;

use App\Entity\Session;
use App\Entity\Stagiaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class SessionType extends AbstractType
{
    // formulaire d'ajout session
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre', TextType::class, [
            'attr' => [
                'class' => 'edit'
            ]])
            ->add('nbPlace', NumberType::class, [
                'attr' => [
                    'class' => 'edit'
                ]])
            ->add('dateDebut', DateType::class, [
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'edit'
                ]
            ])
            ->add('dateFin', DateType::class, [
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'edit'
                ]
            ])
            // ->add('inscriptions', EntityType::class, [
            //     'class' => Stagiaire::class,
            //     'choice_label' => 'nom',
            //     'multiple' => true,
            // ])
            ->add('valider', SubmitType::class, [
                'attr' => [
                    'class' => 'edit btn btn-secondary'
                ]])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Session::class,
        ]);
    }
}

src/Controller/SessionController.php
<?php

namespace App\Controller;

use App\Entity\Section;
use App\Entity\Session;
use App\Entity\Programme;
use App\Entity\Stagiaire;
use App\Form\SessionType;
use App\Form\ProgrammeType;
use App\Form\StagiaireType;
use App\Repository\SectionRepository;
use App\Repository\SessionRepository;
use App\Repository\ProgrammeRepository;
use App\Repository\StagiaireRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class SessionController extends AbstractController
{

    // récupère liste des sessions 
    #[Route('/session', name: 'app_session')]
    public function index(SessionRepository $sessionRepository): Response
    {
        $sessions = $sessionRepository->findBy([], ["id" => "ASC"]);
        return $this->render('session/index.html.twig', [
            'sessions' => $sessions
        ]);
    }
    
    // crée le formulaire et rajoute session dans bdd ou modifie session 
    #[Route('session/new', name: 'new_session')]
    #[Route('/session/{id}/edit', name: 'edit_session')]
    public function new_edit(Session $session = null, Request $request, EntityManagerInterface $entityManager): Response
    {
        if($this->getUser())
        {
            if(!$session)
            {
                $session = new Session();
            }
            
            $form = $this->createForm(SessionType::class, $session);
    
            $form->handleRequest($request);
    
            if($form->isSubmitted() && $form->isValid())
            {
                $employe = $form->getData();
                //prepare PDO
                $entityManager->persist($employe);
                //execute PDO
                $entityManager->flush();
    
                return $this->redirectToRoute('app_session');
            }
            // session/new.html.twig-> on définit l'endroit ou on veut faire passer les données, puis les données qu'on veut faire passer [clé=>valeur]
            return $this->render('session/new.html.twig', [
                'formAddSession' => $form,
                'edit' => $session->getId()
            ]);
        }else
        {
            return $this->redirectToRoute('app_login');
        }

    }

    // supprime session 
    #[Route('/session/{id}/delete', name: 'delete_session')]
    public function delete(Session $session, EntityManagerInterface $entityManager): Response
    {
        $entityManager->remove($session);
        $entityManager->flush();

        return $this->redirectToRoute('app_session');
    }

    // détail programme d'une session + ajout programme
    #[Route('/session/{id}', name: 'show_session')]
    #[Route('/session/{id}/addProg', name: 'addProg_programme')]
    public function show(Session $session, StagiaireRepository $stagiaireRepository, SessionRepository $sr, Request $request, EntityManagerInterface $entityManager): Response
    {
         // Création nouvelle instance de Programme
        $programme = new Programme();
        $sections = $sr->findProgsNoSession($session->getId());
        // Création du formulaire ProgrammeType et le liez à l'entité Programme
        $form = $this->createForm(ProgrammeType::class, $programme, [
            'sections' => $sections
        ]);

        // Gérez les données du formulaire lorsqu'il est soumis
        $form->handleRequest($request);

        // Vérification soumission et validité formulaire
        if ($form->isSubmitted() && $form->isValid()) {
            // Enregistrement base de données
            $entityManager->persist($programme);
            $entityManager->flush();

            // renvoie message en cas de succès 
            // $this->addFlash('success', 'Le programme a été ajouté avec succès.');

            // Redirection
            return $this->redirectToRoute('show_session', ['id' => $session->getId()]);
        }

        $inscription = $session->getInscriptions();
        $stagiaires = $stagiaireRepository->findBy([], ["nom" => "ASC"]);
        $nonInscrits = $sr->findNonInscrits($session->getId());
        $findProgsNoSession = $sr->findProgsNoSession($session->getId());
        $sessions = $sr->findBy(['id' => $session], ["id" => "ASC"]);
        return $this->render('session/show.html.twig', [
            'sessions' => $session,
            'stagiaires' => $stagiaires,
            'inscriptions' => $inscription,
            'nonInscrits' => $nonInscrits,
            'formAddProgramme' => $form,
            'placeSessions' => $sessions,
            'findProgsNoSession' => $findProgsNoSession
        ]);
    }

    // affiche liste des stagiaires inscrit à une session
    #[Route('/session/{id}/listInscription', name: 'listInscription_session')]
    public function listInscription(Session $session = null, StagiaireRepository $stagiaireRepository, SessionRepository $sr): Response
    {
        
        $inscription = $session->getInscriptions();
        $stagiaires = $stagiaireRepository->findBy([], ["nom" => "ASC"]);
        $nonInscrits = $sr->findNonInscrits($session->getId());
        return $this->render('session/listInscription.html.twig', [
            'sessions' => $session,
            'stagiaires' => $stagiaires,
            'inscriptions' => $inscription,
            'nonInscrits' => $nonInscrits
        ]);
    }

    // ajoute stagiaire à une session 
    #[Route('/session/{id}/addStagiaire', name: 'addStagiaire_session')]
    public function addStagiaire(Request $request, $id, StagiaireRepository $stagiaireRepository, SessionRepository $sessionRepository, EntityManagerInterface $entityManager)
    {
        // Récupérer la session en fonction de l'ID passé dans l'URL
        $session = $sessionRepository->find($id);

        // Vérifier si la session existe
        if (!$session) {
            echo 'La session n\'existe pas.';
        }

        // Récupérer l'ID du stagiaire à partir des données du formulaire
        $stagiaireId = $request->request->get('stagiaire');

        // Récupérer le stagiaire en fonction de l'ID
        $stagiaire = $stagiaireRepository->find($stagiaireId);

        // Vérifier si le stagiaire existe
        if (!$stagiaire) {
            echo 'Le stagiaire n\'existe pas.';
        }

        // Ajouter le stagiaire à la session
        $session->addInscription($stagiaire);

        // Enregistrer les modifications en base de données
        $entityManager->flush();

        // Rediriger vers une page de confirmation ou autre
        return $this->redirectToRoute('show_session', ['id' => $session->getId()]);
        // return $this->redirectToRoute('addStagiaire_session', ['id' => $session->getId()]);
    }

    // supprime stagiaire inscrit à une session 
    #[Route('/session/{id}/deleteStagiaire/{inscriptionId}', name: 'deleteStagiaire_session')]
    public function deleteStagiaireSession(Session $session, Stagiaire $inscriptionId, EntityManagerInterface $entityManager): Response
    {
        $session->removeInscription($inscriptionId);
        $entityManager->flush();

        return $this->redirectToRoute('show_session', ['id' => $session->getId()]);
    }
    
    #[Route('/session/{id}/addModule', name: 'addModule_session')]
public function addModule(Session $session, Request $request, SectionRepository $sectionRepository, EntityManagerInterface $entityManager)
{
    // Vérifier si la session existe
    if (!$session) {
        throw $this->createNotFoundException('La session n\'existe pas.');
    }

    // Récupérer les données du formulaire
    $moduleId = $request->request->get('module');
    $duree = $request->request->get('duree');

    // Récupérer le module en fonction de l'ID
    $module = $sectionRepository->find($moduleId);

    // Vérifier si le module existe
    if (!$module) {
        throw $this->createNotFoundException('Le module n\'existe pas.');
    }

    // Créer un nouvel objet Programme
    $programme = new Programme();
    $programme->setSession($session);
    $programme->setSection($module);
    $programme->setDuree($duree);

    // Enregistrer le programme en base de données
    $entityManager->persist($programme);
    $entityManager->flush();

    // Rediriger vers une page de confirmation ou autre
    return $this->redirectToRoute('show_session', ['id' => $session->getId()]);
}

    

    // supprime programme d'une session 
    #[Route('/session/{id}/deleteProgramme/{programmeId}', name: 'deleteProgramme_session')]
    public function deleteProgrammeSession(Session $session, Programme  $programmeId, EntityManagerInterface $entityManager): Response
    {
        
        $entityManager->remove($programmeId);
        $entityManager->flush();

        return $this->redirectToRoute('show_session', ['id' => $session->getId()]);
    }



}

templates/session/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste session{% endblock %}

{% block body %}
    {% if app.user %}
    <div class="login">
      <h1>Bonjour {{ app.user.pseudo }}  </h1>
      
      <a class="btn btn-secondary" href="{{ path('new_session') }}">Ajouter une session</a><br>
    </div>
    
      {# affichage liste session  #}

      <div class="row">
        {% for session in sessions %}
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ session.titre }}</h5>
                    <p class="ligne">Période du : {{ session.dateDebut|date('d-m-Y') ~ ' au ' ~ session.dateFin|date('d-m-Y') }}</p>
                    <div class="button-card">
                      <a href="{{ path('show_session', {'id': session.id}) }}"><i class="fas fa-info-circle"></i></a>
                      <a href="{{ path('edit_session', {'id': session.id}) }}"><i class="fa-solid fa-pen-to-square"></i></a>
                      <a href="{{ path('delete_session', {'id': session.id}) }}"><i class="fa-solid fa-trash"></i></a>
                    </div>
                </div>
            </div>
        {% endfor %}
      </div>
                {# <table class="table-bordered">
                    <thead>
                      <tr>
                        <th class="th" scope="col">Intitulé et date Session</th>
                        <th class="th" scope="col">Supprimer</th>
                        <th class="th" scope="col">Editer</th>
                        <th class="th" scope="col">Liste participant</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for session in sessions %}
                        <tr>
                          <th scope="row"><p class="titre"><h5>{{ session.titre ~ ' ( du ' ~ session.dateDebut|date('d-m-Y') ~ ' au ' ~ session.dateFin|date('d-m-Y') ~ ' ) ' }} <a href="{{ path('show_session', {'id': session.id}) }}"><i class="fa-solid fa-book"></i></a></p></th>
                          <td><a href="{{ path('delete_session', {'id': session.id}) }}"><i class="fa-solid fa-trash"></i></a></td>
                          <td><a href="{{ path('edit_session', {'id': session.id}) }}"><i class="fa-solid fa-pen-to-square"></i></a></td>
                          <td><a href="{{ path('listInscription_session', {'id': session.id}) }}"><i class="fa-solid fa-users"></i></a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
        </div> #}
    {% else %}
        <meta http-equiv="refresh" content="0;url={{ path('app_login') }}">
    {% endif %}
    
    
{% endblock %}

templates/session/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter Session{% endblock %}

{% block body %}
<div class="login">
    {% if edit %}
    <h1>Editer une session</h1> 
    {% else %}
    <h1>Ajouter une session</h1>
    {% endif %}

<div class="list-form">

    {# formulaire ajout et edit session  #}
    {{ form_start(formAddSession) }}
    {{ form_row(formAddSession.titre) }}
    {{ form_row(formAddSession.nbPlace) }}
    {{ form_row(formAddSession.dateDebut) }}
    {{ form_row(formAddSession.dateFin) }}
    {{ form_end(formAddSession) }}
</div>
</div>

    
{% endblock %}

templates/session/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Programme session{% endblock %}

{% block body %}
        {% if app.user %}
<div class="">
    <div class="section1">
        <span class="login">
            <h1>Formation {{ sessions.formation.intitule }} </h1>
            <h2> {{ sessions.titre ~ ' ( du ' ~ sessions.dateDebut|date('d-m-Y') ~ ' au ' ~ sessions.dateFin|date('d-m-Y') ~ ' ) ' }} </h2>
            <h3>Dispensée par : {{ sessions.formateur.nom ~ ' ' ~ sessions.formateur.prenom }} </h3>
            {% for placeSession in placeSessions %}
            <div class="">
                <div class="card-body">
                    <h5 class="detail-place">Nb places : {{ placeSession.nbPlace }}</h5>
                    <h5 class="detail-place">Nb places reservées : {{ placeSession.nbInscrit }}</h5>
                    <h5 class="detail-place">Nb places restantes : {{ placeSession.nbPlacesRestantes }}</h5>
                </div>
            </div>
            {% endfor %}
        </span>
        <span class="login">
            <h2>Liste stagiaire inscrit</h2>
        </span>
        <span class="list">
            <span class="login">
                {# liste inscription session  #}
                {% if inscriptions | length == 0 %}
                    <p>Pas d'inscrits</p>
                {% else %}
                <div class="row">
                    {% for inscrit in sessions.inscriptions %}
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title"><a href="{{ path('show_stagiaire', {'id': inscrit.id}) }}">{{ inscrit }}</a></h5>
                                    <p class="ligne">Courriel : {{ inscrit.email }} </p>
                                    <p>Adresse : {{ inscrit.adresse }} </p>
                                    <p class="ligne">{{ inscrit.cp ~ ' ' ~ inscrit.ville|capitalize }} </p>
                                <div class="button-card">
                                    <a href="{{ path('deleteStagiaire_session', {'id': sessions.id, 'inscriptionId': inscrit.id}) }}"><i class="fa-solid fa-trash"></i></a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {% endif %}
            </span>
        
           
                {# Formulaire inscription session #}
                {% if nonInscrits | length == 0  %}
                    <h5>Tous les stagiaires sont inscrit à la session</h5>
                    {% else %}
                    <form class="form" action="{{ path('addStagiaire_session', {'id': sessions.id}) }}" method="post">
                        <label for="select">Veuillez selectionnez le stagiaire pour l'ajouter à la liste</label><br>
                            <select class="edit-1" name="stagiaire">
                                {% for nonInscrit in nonInscrits %}
                                    <option class="edit-1"   value="{{ nonInscrit.id }}">{{ nonInscrit.nom }} {{ nonInscrit.prenom }}</option>
                                {% endfor %}
                            </select>
                        <button class="btn btn-secondary edit-1" type="submit">Ajouter</button>
                    </form>
                {% endif %}
        </div>
    <div class="section2">
        {# affiche programme session  #}
        <span class="login">
            <h2>Programme session</h2>
                <div class="row">
                    {% for prog in sessions.programmes %}
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">{{ prog.section.nomSection }}</h5>
                                <p class="ligne">Durée : {{ prog.duree }} {% if prog.duree > 1 %}
                                    jours
                                {% else %}
                                    jour
                                {% endif %} </p>
                                <div class="button-card">
                                    <a href="{{ path('deleteProgramme_session', {'id': sessions.id, 'programmeId': prog.id}) }}"><i class="fa-solid fa-trash"></i></a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </span>
    <div class="section4">
        {# ajoute programme #}
        <span class="login">
            <form class="form-prog"  action="{{ path('addModule_session', {'id': sessions.id}) }}" method="post">
                <label for="duree">Durée</label><br>
                    <input class="edit" type="number" name="duree" required>
                    <label for="select">Veuillez sélectionner le module pour l'ajouter à la liste</label><br>
                    <select class="edit" name="module">
                        {% for findProgNoSession in findProgsNoSession %}
                            <option class="edit" value="{{ findProgNoSession.id }}">{{ findProgNoSession.nomSection }}</option>
                        {% endfor %}
                    </select>
                <button class="btn btn-secondary edit" type="submit">Ajouter</button>
            </form>
        </span>

        {# message flash succès ajout  #}
        {% for flash_message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ flash_message }}
        
        </div>
    </div>
            {% endfor %}
                {% else %}
                    <meta http-equiv="refresh" content="0;url={{ path('app_login') }}">
                {% endif %}
                
       
{% endblock %}